name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build C# code
      run: dotnet build

    - name: Run C# Tests
      run: dotnet test
      working-directory: ./DotnetTemplate.Web    

    - name: Build TypeScript code
      run: | 
        npm ci
        npm run build
      working-directory: ./DotnetTemplate.Web

    - name: Linting on TypeScript code
      run: npm run lint
      working-directory: ./DotnetTemplate.Web

    - name: Run TypeScript tests
      run: npm t
      working-directory: ./DotnetTemplate.Web

    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "morning-retreat-83411" #Must be unique in Heroku
          heroku_email: "simeon_penev@hotmail.com"
          usedocker: true
          